apiVersion: v1
kind: ConfigMap
metadata:
  name: stocksapp-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__ContactDb: "Server=db-service,1433;Database=ContectManagerDB;User Id=sa;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True;"
  ConnectionStrings__StocksDbConnection: "Server=db-service,1433;Database=StocksDb;User Id=sa;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True;"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  ACCEPT_EULA: "Y"
  MSSQL_ENABLE_HADR: "1"
  MSSQL_AGENT_ENABLED: "1"