apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-database
spec:
  serviceName: "app-database"
  replicas: 1
  selector:
    matchLabels:
      app: app-database
  template:
    metadata:
      labels:
        app: app-database
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: app-database
        image: mcr.microsoft.com/mssql/server:2022-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
          name: tcpsql
        envFrom:
        - configMapRef:
            name: database-config
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stocksapp-secret
              key: SA_PASSWORD
        volumeMounts:
        - name: app-database-storage
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -Q 'SELECT 1' -No"
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $MSSQL_SA_PASSWORD -Q 'SELECT 1' -No"
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
  volumeClaimTemplates:
  - metadata:
      name: app-database-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi